//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloAAEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adquieren
    {
        public string nroPasaporte { get; set; }
        public int nroTicket { get; set; }
        public int nroAsiento { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
