//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloAAEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuertos
    {
        public string codigoA { get; set; }
        public string nombreA { get; set; }
        public string direccion { get; set; }
        public double impuestoPartida { get; set; }
        public double impuestoLlegada { get; set; }
        public string codigoC { get; set; }
        public bool activo { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
    }
}
