//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloAAEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public string codigoV { get; set; }
        public System.DateTime fechaD { get; set; }
        public System.DateTime fechaA { get; set; }
        public double precio { get; set; }
        public int cantAsientos { get; set; }
        public string codigoA { get; set; }
        public string codigoB { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        public virtual Aeropuertos Aeropuertos1 { get; set; }
    }
}
